# https://docs.travis-ci.com/user/customizing-the-build
language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: default
    token:
      secure: $SONAR_TOKEN

script: mvn install -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} == "master" ]; then mvn sonar:sonar -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6b2b280eb5f8bd67d54c
    on_success: change
    on_failure: always
    on_start: never
