# https://docs.travis-ci.com/user/customizing-the-build
language: java
jdk: oraclejdk8
addons:
  sonarqube: true
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2
    - /var/cache/apt
install: mvn install -DskipTests=true -B -V
script: mvn verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6b2b280eb5f8bd67d54c
    on_success: change
    on_failure: always
    on_start: never