# https://docs.travis-ci.com/user/customizing-the-build
language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: default
    token:
      secure: $SONAR_TOKEN
install: mvn dependency:resolve dependency:resolve-plugins
script: mvn verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} == "master" ]; then mvn sonar:sonar; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6b2b280eb5f8bd67d54c
    on_success: change
    on_failure: always
    on_start: never
